### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by MochamadLukyAdithia** [MochamadLukyAdithia/ProjekPBO#2]

**Comment by vanvl49** [comment]
Daftar Entity dan Atributnya (Work In Progress) 

https://docs.google.com/document/d/1ks6FPPPB_8_-_dKVR-dxk_9m8Ngy1Wj05u7jgXo3Ewo/edit?hl=id

**Comment by ristigadis** [comment]
[ERD PBO PROJEK LOGICAL.pdf](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14940744/ERD.PBO.PROJEK.LOGICAL.pdf)
Dikerjakan oleh : Syavana Salsabila (2029), Risti Gadis Astiyanto (2031), Lutfi Arif Widianto (2035)

**Comment by vanvl49** [comment]
[
[ERD PBO PROJECT PHYSICAL-rev.pdf](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14947270/ERD.PBO.PROJECT.PHYSICAL-rev.pdf)
[ERD PBO PROJECT LOGICAL-rev.pdf](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14947273/ERD.PBO.PROJECT.LOGICAL-rev.pdf)
](url)

Revisi ERD 
Dikerjakan oleh : Syavana Salsabila (2029), Risti Gadis Astiyanto (2031), Lutfi Arif Widianto (2035)

**Comment by vanvl49** [comment]
[ERD PBO PROJEK.zip](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14947313/ERD.PBO.PROJEK.zip)

FILE DMD ERD
Dikerjakan oleh : Syavana Salsabila (2029), Risti Gadis Astiyanto (2031), Lutfi Arif Widianto (2035)

**Comment by vanvl49** [comment]
[ERD PBO PROJECT LOGICAL-rev2.pdf](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14971369/ERD.PBO.PROJECT.LOGICAL-rev2.pdf)
[ERD PBO PROJECT PHYSICAL-rev2.pdf](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14971370/ERD.PBO.PROJECT.PHYSICAL-rev2.pdf)

revisi ERD 2 14-04-2024 = 
- menambahkan atribut nomor rekening di entity user, admin pusat, admin pengepul (optional)
- menambahkan atribut username & password  di entity user, admin pusat, admin pengepul
- menambahkan entity Penjualan yang memiliki relasi dengan entity admin (pengepul) dan admin (pusat) dengan atribut : 
          1. Tanggal 
          2. Jumlah Biji Kopi
          3. Harga 
          4. Metode Pembayaran (optional, 
              memiliki default value transfer)
