### ISSUE TITLE
Navigation Map

### ISSUE THREAD

**Issue by MochamadLukyAdithia** [MochamadLukyAdithia/ProjekPBO#4]

**Comment by vanvl49** [comment]
Daftar Entity dan atributnya (Work In progress) : 
[https://docs.google.com/document/d/1ks6FPPPB_8_-_dKVR-dxk_9m8Ngy1Wj05u7jgXo3Ewo/edit?hl=id](url)

**Comment by landcya** [comment]
[](url)

[Penjelasan Navigation Map..docx](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14947487/Penjelasan.Navigation.Map.docx)

**Comment by landcya** [comment]
[C:\Users\user\Downloads\Penjelasan.Navigation.Map (4).docx](url)

**Comment by landcya** [comment]
[C:\Users\user\Downloads\Penjelasan.Navigation.Map.docx](url)

**Comment by landcya** [comment]
[https://docs.google.com/document/d/1Vl1CXaTFOcxGsYEHefF1MAKZNogisxwhHqYlIzhLOiQ/edit?usp=sharing](url)

**Comment by landcya** [comment]
[file:///C:/Users/user/Downloads/Penjelasan-Navigation-Map.html](url)

**Comment by landcya** [comment]
[https://docs.google.com/document/d/1Vl1CXaTFOcxGsYEHefF1MAKZNogisxwhHqYlIzhLOiQ/edit?usp=sharing](url)
