### ISSUE TITLE
MockUP

### ISSUE THREAD

**Issue by MochamadLukyAdithia** [MochamadLukyAdithia/ProjekPBO#5]

**Comment by HashSlingingSlasherrPAN** [comment]
[User_Mockup_Desain_App.pdf](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14996808/User_Mockup_Desain_App.pdf)

**Comment by HashSlingingSlasherrPAN** [comment]
[User_Mockup_Desain_App.pdf](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14996828/User_Mockup_Desain_App.pdf)

**Comment by WahyuJumahMaulidan** [comment]
[Admin_MockUp_Design_Apps.pdf](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14997073/Admin_MockUp_Design_Apps.pdf)

**Comment by AlfinMiftakhurRohman** [comment]
[Pusat_MockUp_Design_Apps.pdf](https://github.com/MochamadLukyAdithia/ProjekPBO/files/14997139/Pusat_MockUp_Design_Apps.pdf)
